module.exports = {
    "response": {
        "version":"0.1",
        "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
        "features": {
            "hourly": 1
        }
    }
    ,
    "hourly_forecast": [
	{
	    "FCTTIME": {
		"hour": "16",
                "hour_padded": "16",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502658000",
                "pretty": "4:00 PM CDT on August 13, 2017",
                "civil": "4:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "87",
                     "metric": "31"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "74",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "NW",
                     "degrees": "321"},
	    "wx": "Mostly Cloudy",
	    "uvi": "4",
	    "humidity": "63",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "94",
                          "metric": "34"},
	    "feelslike": {"english": "94",
                          "metric": "34"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "0",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "17",
                "hour_padded": "17",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502661600",
                "pretty": "5:00 PM CDT on August 13, 2017",
                "civil": "5:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "86",
                     "metric": "30"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "76",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "NNW",
                     "degrees": "339"},
	    "wx": "Mostly Cloudy",
	    "uvi": "1",
	    "humidity": "64",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "92",
                          "metric": "33"},
	    "feelslike": {"english": "92",
                          "metric": "33"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "0",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "18",
                "hour_padded": "18",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502665200",
                "pretty": "6:00 PM CDT on August 13, 2017",
                "civil": "6:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "85",
                     "metric": "29"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "75",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "NNW",
                     "degrees": "343"},
	    "wx": "Mostly Cloudy",
	    "uvi": "1",
	    "humidity": "65",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "0",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "19",
                "hour_padded": "19",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502668800",
                "pretty": "7:00 PM CDT on August 13, 2017",
                "civil": "7:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "83",
                     "metric": "28"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "76",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "N",
                     "degrees": "11"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "69",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "87",
                          "metric": "31"},
	    "feelslike": {"english": "87",
                          "metric": "31"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "0",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "20",
                "hour_padded": "20",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502672400",
                "pretty": "8:00 PM CDT on August 13, 2017",
                "civil": "8:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "80",
                     "metric": "27"},
	    "dewpoint": {"english": "71",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "68",
	    "wspd": {"english": "4",
                     "metric": "6"},
	    "wdir": {"dir": "NE",
                     "degrees": "38"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "76",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "85",
                          "metric": "29"},
	    "feelslike": {"english": "80",
                          "metric": "27"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "3",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "21",
                "hour_padded": "21",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502676000",
                "pretty": "9:00 PM CDT on August 13, 2017",
                "civil": "9:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "78",
                     "metric": "26"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "69",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "NE",
                     "degrees": "49"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "82",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "78",
                          "metric": "26"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "5",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "22",
                "hour_padded": "22",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502679600",
                "pretty": "10:00 PM CDT on August 13, 2017",
                "civil": "10:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "77",
                     "metric": "25"},
	    "dewpoint": {"english": "72",
                         "metric": "22"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "86",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "NE",
                     "degrees": "54"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "85",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "77",
                          "metric": "25"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "23",
                "hour_padded": "23",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "13",
                "mday_padded": "13",
                "yday": "224",
                "isdst": "1",
                "epoch": "1502683200",
                "pretty": "11:00 PM CDT on August 13, 2017",
                "civil": "11:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Sunday",
                "weekday_name_night": "Sunday Night",
                "weekday_name_abbrev": "Sun",
                "weekday_name_unlang": "Sunday",
                "weekday_name_night_unlang": "Sunday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "77",
                     "metric": "25"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "97",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "NE",
                     "degrees": "56"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "88",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "77",
                          "metric": "25"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "0",
                "hour_padded": "00",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502686800",
                "pretty": "12:00 AM CDT on August 14, 2017",
                "civil": "12:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "93",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "ENE",
                     "degrees": "77"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "91",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "1",
                "hour_padded": "01",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502690400",
                "pretty": "1:00 AM CDT on August 14, 2017",
                "civil": "1:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "96",
	    "wspd": {"english": "2",
                     "metric": "3"},
	    "wdir": {"dir": "E",
                     "degrees": "94"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "91",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "2",
                "hour_padded": "02",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502694000",
                "pretty": "2:00 AM CDT on August 14, 2017",
                "civil": "2:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "97",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "E",
                     "degrees": "99"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "90",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "3",
                "hour_padded": "03",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502697600",
                "pretty": "3:00 AM CDT on August 14, 2017",
                "civil": "3:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "97",
	    "wspd": {"english": "4",
                     "metric": "6"},
	    "wdir": {"dir": "ESE",
                     "degrees": "103"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "90",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.88",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "4",
                "hour_padded": "04",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502701200",
                "pretty": "4:00 AM CDT on August 14, 2017",
                "civil": "4:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "75",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "97",
	    "wspd": {"english": "2",
                     "metric": "3"},
	    "wdir": {"dir": "ESE",
                     "degrees": "108"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "92",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "75",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "18",
	    "mslp": {"english": "29.87",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "5",
                "hour_padded": "05",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502704800",
                "pretty": "5:00 AM CDT on August 14, 2017",
                "civil": "5:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "94",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "ESE",
                     "degrees": "123"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "91",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "18",
	    "mslp": {"english": "29.87",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "6",
                "hour_padded": "06",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502708400",
                "pretty": "6:00 AM CDT on August 14, 2017",
                "civil": "6:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "94",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "SE",
                     "degrees": "138"},
	    "wx": "Isolated Thunderstorms",
	    "uvi": "0",
	    "humidity": "90",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "31",
	    "mslp": {"english": "29.87",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "7",
                "hour_padded": "07",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502712000",
                "pretty": "7:00 AM CDT on August 14, 2017",
                "civil": "7:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "73",
                         "metric": "23"},
	    "condition": "Chance of Rain",
	    "icon": "chancerain",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancerain.gif",
	    "fctcode": "12",
	    "sky": "84",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "SSE",
                     "degrees": "149"},
	    "wx": "Showers",
	    "uvi": "0",
	    "humidity": "91",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.06",
                    "metric": "2"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "42",
	    "mslp": {"english": "29.88",
                     "metric": "1012"}
	},
	{
	    "FCTTIME": {
		"hour": "8",
                "hour_padded": "08",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502715600",
                "pretty": "8:00 AM CDT on August 14, 2017",
                "civil": "8:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "74",
                         "metric": "23"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
	    "fctcode": "4",
	    "sky": "90",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "SSE",
                     "degrees": "159"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "92",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "24",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "9",
                "hour_padded": "09",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502719200",
                "pretty": "9:00 AM CDT on August 14, 2017",
                "civil": "9:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "78",
                     "metric": "26"},
	    "dewpoint": {"english": "74",
                         "metric": "23"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "79",
	    "wspd": {"english": "5",
                     "metric": "8"},
	    "wdir": {"dir": "S",
                     "degrees": "180"},
	    "wx": "Scattered Thunderstorms",
	    "uvi": "2",
	    "humidity": "88",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "78",
                          "metric": "26"},
	    "qpf": {"english": "0.04",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "55",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "10",
                "hour_padded": "10",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502722800",
                "pretty": "10:00 AM CDT on August 14, 2017",
                "civil": "10:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "79",
                     "metric": "26"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Thunderstorm",
	    "icon": "tstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/tstorms.gif",
	    "fctcode": "15",
	    "sky": "90",
	    "wspd": {"english": "8",
                     "metric": "13"},
	    "wdir": {"dir": "SSW",
                     "degrees": "205"},
	    "wx": "Thunderstorms",
	    "uvi": "2",
	    "humidity": "86",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "79",
                          "metric": "26"},
	    "qpf": {"english": "0.06",
                    "metric": "2"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "74",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "11",
                "hour_padded": "11",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502726400",
                "pretty": "11:00 AM CDT on August 14, 2017",
                "civil": "11:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "78",
                     "metric": "26"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Thunderstorm",
	    "icon": "tstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/tstorms.gif",
	    "fctcode": "15",
	    "sky": "88",
	    "wspd": {"english": "6",
                     "metric": "10"},
	    "wdir": {"dir": "SW",
                     "degrees": "217"},
	    "wx": "Thunderstorms",
	    "uvi": "3",
	    "humidity": "89",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "78",
                          "metric": "26"},
	    "qpf": {"english": "0.05",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "75",
	    "mslp": {"english": "29.91",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "12",
                "hour_padded": "12",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502730000",
                "pretty": "12:00 PM CDT on August 14, 2017",
                "civil": "12:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "80",
                     "metric": "27"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Thunderstorm",
	    "icon": "tstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/tstorms.gif",
	    "fctcode": "15",
	    "sky": "89",
	    "wspd": {"english": "8",
                     "metric": "13"},
	    "wdir": {"dir": "SW",
                     "degrees": "221"},
	    "wx": "Thunderstorms",
	    "uvi": "4",
	    "humidity": "85",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "86",
                          "metric": "30"},
	    "feelslike": {"english": "80",
                          "metric": "27"},
	    "qpf": {"english": "0.04",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "66",
	    "mslp": {"english": "29.9",
                     "metric": "1013"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "13",
                "hour_padded": "13",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502733600",
                "pretty": "1:00 PM CDT on August 14, 2017",
                "civil": "1:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "83",
                     "metric": "28"},
	    "dewpoint": {"english": "76",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "78",
	    "wspd": {"english": "9",
                     "metric": "14"},
	    "wdir": {"dir": "WSW",
                     "degrees": "247"},
	    "wx": "Isolated Thunderstorms",
	    "uvi": "6",
	    "humidity": "79",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.01",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "34",
	    "mslp": {"english": "29.88",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "14",
                "hour_padded": "14",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502737200",
                "pretty": "2:00 PM CDT on August 14, 2017",
                "civil": "2:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "82",
                     "metric": "28"},
	    "dewpoint": {"english": "76",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "94",
	    "wspd": {"english": "8",
                     "metric": "13"},
	    "wdir": {"dir": "WSW",
                     "degrees": "238"},
	    "wx": "Scattered Thunderstorms",
	    "uvi": "4",
	    "humidity": "82",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.01",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "35",
	    "mslp": {"english": "29.86",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "15",
                "hour_padded": "15",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502740800",
                "pretty": "3:00 PM CDT on August 14, 2017",
                "civil": "3:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "82",
                     "metric": "28"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "93",
	    "wspd": {"english": "9",
                     "metric": "14"},
	    "wdir": {"dir": "WSW",
                     "degrees": "241"},
	    "wx": "Scattered Thunderstorms",
	    "uvi": "3",
	    "humidity": "79",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.03",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "53",
	    "mslp": {"english": "29.85",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "16",
                "hour_padded": "16",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502744400",
                "pretty": "4:00 PM CDT on August 14, 2017",
                "civil": "4:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "83",
                     "metric": "28"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "86",
	    "wspd": {"english": "9",
                     "metric": "14"},
	    "wdir": {"dir": "WSW",
                     "degrees": "242"},
	    "wx": "Scattered Thunderstorms",
	    "uvi": "3",
	    "humidity": "78",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.02",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "43",
	    "mslp": {"english": "29.84",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "17",
                "hour_padded": "17",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502748000",
                "pretty": "5:00 PM CDT on August 14, 2017",
                "civil": "5:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "83",
                     "metric": "28"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "88",
	    "wspd": {"english": "8",
                     "metric": "13"},
	    "wdir": {"dir": "WSW",
                     "degrees": "254"},
	    "wx": "Isolated Thunderstorms",
	    "uvi": "1",
	    "humidity": "78",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.02",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "30",
	    "mslp": {"english": "29.84",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "18",
                "hour_padded": "18",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502751600",
                "pretty": "6:00 PM CDT on August 14, 2017",
                "civil": "6:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "82",
                     "metric": "28"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Chance of a Thunderstorm",
	    "icon": "chancetstorms",
	    "icon_url":"http://icons.wxug.com/i/c/k/chancetstorms.gif",
	    "fctcode": "14",
	    "sky": "82",
	    "wspd": {"english": "7",
                     "metric": "11"},
	    "wdir": {"dir": "WSW",
                     "degrees": "251"},
	    "wx": "Isolated Thunderstorms",
	    "uvi": "0",
	    "humidity": "79",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "90",
                          "metric": "32"},
	    "feelslike": {"english": "90",
                          "metric": "32"},
	    "qpf": {"english": "0.02",
                    "metric": "1"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "30",
	    "mslp": {"english": "29.84",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "19",
                "hour_padded": "19",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502755200",
                "pretty": "7:00 PM CDT on August 14, 2017",
                "civil": "7:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "80",
                     "metric": "27"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/cloudy.gif",
	    "fctcode": "4",
	    "sky": "85",
	    "wspd": {"english": "6",
                     "metric": "10"},
	    "wdir": {"dir": "WSW",
                     "degrees": "259"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "84",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "86",
                          "metric": "30"},
	    "feelslike": {"english": "80",
                          "metric": "27"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "21",
	    "mslp": {"english": "29.85",
                     "metric": "1011"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "20",
                "hour_padded": "20",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502758800",
                "pretty": "8:00 PM CDT on August 14, 2017",
                "civil": "8:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "78",
                     "metric": "26"},
	    "dewpoint": {"english": "76",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "89",
	    "wspd": {"english": "4",
                     "metric": "6"},
	    "wdir": {"dir": "WSW",
                     "degrees": "259"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "92",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "78",
                          "metric": "26"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "20",
	    "mslp": {"english": "29.87",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "21",
                "hour_padded": "21",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502762400",
                "pretty": "9:00 PM CDT on August 14, 2017",
                "civil": "9:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "77",
                     "metric": "25"},
	    "dewpoint": {"english": "76",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "87",
	    "wspd": {"english": "4",
                     "metric": "6"},
	    "wdir": {"dir": "S",
                     "degrees": "173"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "95",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "77",
                          "metric": "25"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "19",
	    "mslp": {"english": "29.88",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "22",
                "hour_padded": "22",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502766000",
                "pretty": "10:00 PM CDT on August 14, 2017",
                "civil": "10:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "90",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "SSW",
                     "degrees": "214"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "96",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "24",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "23",
                "hour_padded": "23",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "14",
                "mday_padded": "14",
                "yday": "225",
                "isdst": "1",
                "epoch": "1502769600",
                "pretty": "11:00 PM CDT on August 14, 2017",
                "civil": "11:00 PM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Monday",
                "weekday_name_night": "Monday Night",
                "weekday_name_abbrev": "Mon",
                "weekday_name_unlang": "Monday",
                "weekday_name_night_unlang": "Monday Night",
                "ampm": "PM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "76",
                     "metric": "24"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "86",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "SSW",
                     "degrees": "209"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "98",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "76",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "24",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "0",
                "hour_padded": "00",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "15",
                "mday_padded": "15",
                "yday": "226",
                "isdst": "1",
                "epoch": "1502773200",
                "pretty": "12:00 AM CDT on August 15, 2017",
                "civil": "12:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Tuesday",
                "weekday_name_night": "Tuesday Night",
                "weekday_name_abbrev": "Tue",
                "weekday_name_unlang": "Tuesday",
                "weekday_name_night_unlang": "Tuesday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "75",
                     "metric": "24"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Overcast",
	    "icon": "cloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_cloudy.gif",
	    "fctcode": "4",
	    "sky": "80",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "S",
                     "degrees": "191"},
	    "wx": "Cloudy",
	    "uvi": "0",
	    "humidity": "100",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "75",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "24",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "1",
                "hour_padded": "01",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "15",
                "mday_padded": "15",
                "yday": "226",
                "isdst": "1",
                "epoch": "1502776800",
                "pretty": "1:00 AM CDT on August 15, 2017",
                "civil": "1:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Tuesday",
                "weekday_name_night": "Tuesday Night",
                "weekday_name_abbrev": "Tue",
                "weekday_name_unlang": "Tuesday",
                "weekday_name_night_unlang": "Tuesday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "75",
                     "metric": "24"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "76",
	    "wspd": {"english": "2",
                     "metric": "3"},
	    "wdir": {"dir": "SW",
                     "degrees": "225"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "100",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "75",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "2",
                "hour_padded": "02",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "15",
                "mday_padded": "15",
                "yday": "226",
                "isdst": "1",
                "epoch": "1502780400",
                "pretty": "2:00 AM CDT on August 15, 2017",
                "civil": "2:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Tuesday",
                "weekday_name_night": "Tuesday Night",
                "weekday_name_abbrev": "Tue",
                "weekday_name_unlang": "Tuesday",
                "weekday_name_night_unlang": "Tuesday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "75",
                     "metric": "24"},
	    "dewpoint": {"english": "75",
                         "metric": "24"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "73",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "SSW",
                     "degrees": "210"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "100",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "75",
                          "metric": "24"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
	,
	{
	    "FCTTIME": {
		"hour": "3",
                "hour_padded": "03",
                "min": "00",
                "min_unpadded": "0",
                "sec": "0",
                "year": "2017",
                "mon": "8",
                "mon_padded": "08",
                "mon_abbrev": "Aug",
                "mday": "15",
                "mday_padded": "15",
                "yday": "226",
                "isdst": "1",
                "epoch": "1502784000",
                "pretty": "3:00 AM CDT on August 15, 2017",
                "civil": "3:00 AM",
                "month_name": "August",
                "month_name_abbrev": "Aug",
                "weekday_name": "Tuesday",
                "weekday_name_night": "Tuesday Night",
                "weekday_name_abbrev": "Tue",
                "weekday_name_unlang": "Tuesday",
                "weekday_name_night_unlang": "Tuesday Night",
                "ampm": "AM",
                "tz": "",
                "age": "",
                "UTCDATE": ""
	    },
	    "temp": {"english": "74",
                     "metric": "23"},
	    "dewpoint": {"english": "74",
                         "metric": "23"},
	    "condition": "Mostly Cloudy",
	    "icon": "mostlycloudy",
	    "icon_url":"http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
	    "fctcode": "3",
	    "sky": "77",
	    "wspd": {"english": "3",
                     "metric": "5"},
	    "wdir": {"dir": "SW",
                     "degrees": "230"},
	    "wx": "Mostly Cloudy",
	    "uvi": "0",
	    "humidity": "100",
	    "windchill": {"english": "-9999",
                          "metric": "-9999"},
	    "heatindex": {"english": "-9999",
                          "metric": "-9999"},
	    "feelslike": {"english": "74",
                          "metric": "23"},
	    "qpf": {"english": "0.0",
                    "metric": "0"},
	    "snow": {"english": "0.0",
                     "metric": "0"},
	    "pop": "15",
	    "mslp": {"english": "29.89",
                     "metric": "1012"}
	}
    ]
};
